---
apiVersion: v1
kind: Service
metadata:
  name: svc-account-app
  namespace: group1-team2
spec:
  selector:
    app: d-group1-team2-account
  ports:
    - protocol: TCP
      port: 8802
      targetPort: 8802
      nodePort: 30222
  type: NodePort

